name: Deploy To Hostinger

on: push

jobs:
  log-event-info:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This workflow was triggered by a ${{ github.event_name }}!"
          echo "REPO: ${{ github.repo }}"
