name: Deploy To Hostinger
on:
  push:
    branches:
      - master

jobs:
  log-event-type:
    runs-on: ubuntu-latest
    steps:
      run: echo 'This workflow was triggered by a ${{ github.event_type }}!'
